name: containers-long-startup

services:
  proxy:
    image: lucaslorentz/caddy-docker-proxy:2.8-alpine
    environment:
      CADDY_INGRESS_NETWORKS: containers-long-startup-core_docker-proxy
    networks:
      - docker-proxy
      - service

  mailer:
    image: schickling/mailcatcher
    labels:
      caddy: https://mailer.localhost
      caddy.reverse_proxy: "{{upstreams http 1080}}"
    networks:
      - docker-proxy
      - mailer

  mariadb:
    image: mariadb:11.0.3
    command: --init-file=/docker-entrypoint-initdb.d/init-db.sql
    environment:
      MARIADB_ROOT_PASSWORD: core
      LANG: "en_US.UTF-8"
      LANGUAGE: "en_US:en"
      TZ: "UTC"
    networks:
      - mariadb

  mysql:
    image: mariadb:10.3.22
    command: --default-authentication-plugin=mysql_native_password
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: main
      LANG: "en_US.UTF-8"
      LANGUAGE: "en_US:en"
      TZ: "Europe/London"
    networks:
      - mysql

  rabbitmq:
    hostname: myrabbitmq
    environment:
      RABBITMQ_DEFAULT_USER: guest
      RABBITMQ_DEFAULT_PASS: guest
    labels:
      caddy: https://rabbitmq.localhost
      caddy.reverse_proxy: "{{upstreams http 15672}}"
    networks:
      - docker-proxy
      - rabbitmq

  redis:
    image: redis:6.2-alpine
    command: redis-server --save 60 1 --loglevel warning
    networks:
      - redis

  minio:
    image: minio/minio:RELEASE.2023-07-21T21-12-44Z.fips
    command: server /data --console-address ":9001"
    environment:
      MINIO_ROOT_USER: root
      MINIO_ROOT_PASSWORD: password
      MINIO_HTTP_TRACE: /var/log/minio.log
    labels:
      caddy: https://minio.localhost
      caddy.reverse_proxy: "{{upstreams http 9001}}"
    networks:
      - docker-proxy
      - s3

networks:
  docker-proxy:
    name: containers-long-startup-core_docker-proxy
  service:
    name: containers-long-startup-core_service
  mariadb:
    name: containers-long-startup-core_mariadb
  mysql:
    name: mysql_mysql
  mailer:
    name: containers-long-startup-core_mailer
  rabbitmq:
    name: rabbitmq_rabbitmq
  redis:
    name: redis_redis
  s3:
    name: s3
