-- This init script runs on every database server restart

CREATE DATABASE IF NOT EXISTS `app-1`;
CREATE DATABASE IF NOT EXISTS `app-2`;
CREATE DATABASE IF NOT EXISTS `app-3`;
CREATE DATABASE IF NOT EXISTS `app-4`;
CREATE DATABASE IF NOT EXISTS `app-5`;
CREATE DATABASE IF NOT EXISTS `app-6`;
CREATE DATABASE IF NOT EXISTS `app-7`;
CREATE DATABASE IF NOT EXISTS `app-8`;
CREATE DATABASE IF NOT EXISTS `app-9`;
CREATE DATABASE IF NOT EXISTS `app-10`;
CREATE DATABASE IF NOT EXISTS `app-11`;
