nelmio_cors:
    defaults:
        origin_regex: false
        allow_credentials: true
        allow_origin: ['*']
        allow_methods: ['GET', 'OPTIONS', 'POST', 'PUT', 'PATCH', 'DELETE']
        allow_headers: ['DNT', 'User-Agent', 'X-Requested-With', 'If-Modified-Since', 'Cache-Control', 'Content-Type', 'Range', 'Authorization', 'Pragma', 'Expires' ,' Referer', 'X-Tenant-Id', 'X-acting-as-user-id', 'X-fingerprint']
        expose_headers: ['Content-Type', 'Content-Range']
        max_age: 3600
